sudo: required
language: php
dist: xenial

matrix:
  include:
    - php: 7.1
      env:
        - DB=mysql-5.7
        - WEBTESTS=false
        - COVERAGE=true
  fast_finish: true

services:
  - memcached
  - mysql

# Prepare the server (PHP, Apache, PHPUnit, APCu etc)
install:
  - chmod +x tests/travis-ci/*.sh
  - tests/travis-ci/setup-server.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE
  - tests/travis-ci/setup-selenium.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Install ElkArte
before_script:
  - tests/travis-ci/setup-elkarte.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Run the PHPUnit tests
script:
  - /var/www/tests/travis-ci/setup-script.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Send coverage reports
after_script:
  - /var/www/tests/travis-ci/setup-results.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE

# Output screen shots, error logs etc
after_failure:
  - /var/www/tests/travis-ci/setup-failure.sh $DB $TRAVIS_PHP_VERSION $WEBTESTS $COVERAGE